### PR TITLE
Added WebTalk Android app - A Video Call app

### PR DESCRIPTION
**Pull request by bhaskarblur**
Hi there, i hope you're doing good.
I've recently worked on Video call app using WebRTC and firebase and wanted to contribute to this Repo with my work.
Kindly review my contribution and merge if valid.

Thank you

### CODE REVIEW

**Comment by bhaskarblur** [comment]
Hi, @SidharthMudgil , Kindly check, Thanks

**Comment by bhaskarblur** [comment]
I will check again, thanks

**Comment by bhaskarblur** [comment]
Now check, thanks @SidharthMudgil

**Comment by SidharthMudgil** [comment]
😐 add little info, screenshots, input, output, demo[optional] follow https://github.com/SidharthMudgil/mini-projects/blob/main/CONTRIBUTING.md

**Comment by bhaskarblur** [comment]
Done, added a readme file for it in the project! :)

**Comment by SidharthMudgil** [comment]
please add screenshots in table format

**Comment by bhaskarblur** [comment]
Done! @SidharthMudgil

**Pull request merged**
