### PR TITLE
Add Three More Projects

### PR DESCRIPTION
**Pull request by newtoallofthis123**
Adds the Following projects

- [x] Cats and Dog
- [x] Medical Costs
- [x] Sentiment Analysis

### CODE REVIEW

**Comment by SidharthMudgil** [comment]
medical cost link not working

**Comment by newtoallofthis123** [comment]
oh yeah! I'll fix that :)

**Comment by newtoallofthis123** [comment]
Check now

**Comment by newtoallofthis123** [comment]
Thanks! Hope the projects help!

**Pull request merged**
