### PR TITLE
Taapmaan-TemperatureConverter project added

### PR DESCRIPTION
**Pull request by Rahullkumr**
Added new flutter mini project

### CODE REVIEW

**Comment by SidharthMudgil** [comment]
Nice app, made these changes too:
- update the project readme for flutter.
- added screenshots in table format like in my mosam app.
- change the name of the project folder like other project names

**Comment by Rahullkumr** [comment]
## Changes to do:

1. update the project readme for flutter.  `done`
2. added screenshots in table format like in my mosam app `done`
3. change the name of the project folder like other project names `done`

**Comment by Rahullkumr** [comment]
please add `Hacktoberfest-accepted` label during merging

**Review by Rahullkumr — COMMENTED** [review]
Everything seems to be alright

**Comment by SidharthMudgil** [comment]
Change project name in snale case.. "project_name" other things are alright

**Comment by Rahullkumr** [comment]
Change project name in snale case.. "project_name" other things are alright . make it like taapman-temperature-converter

# done

**Comment by Rahullkumr** [comment]
Thank you

**Pull request merged**
